map_type: costmap

transform_tolerance: 0.2

obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0

inflation_radius: 0.2
cost_scaling_factor: 10.0

inscribed_radius: 0.35
circumscribed_radius: 0.4

lethal_cost_threshold: 100

observation_sources: base_scan

base_scan: {data_type: LaserScan, expected_update_rate: 0.8, observation_persistence: 0.0, marking: true, clearing: true}

